### ISSUE TITLE
Unable to install cargo-spellcheck due to yanked crate

### ISSUE THREAD

**Issue by laysauchoa** [drahnr/cargo-spellcheck#101]
**Describe the bug**

bindgen = 0.54.1
this crate has been yanked: https://crates.io/crates/bindgen/0.54.1

**To Reproduce**
```
✦ ➜ cargo install cargo-spellcheck --force
    Updating crates.io index
  Installing cargo-spellcheck v0.4.3
error: failed to compile `cargo-spellcheck v0.4.3`, intermediate artifacts can be found at `/tmp/cargo-installFh8W2v`

Caused by:
  failed to select a version for the requirement `bindgen = "^0.54.1"`
  candidate versions found which didn't match: 0.54.0, 0.53.3, 0.53.2, ...
  location searched: crates.io index
required by package `hunspell-sys v0.2.1`
    ... which is depended on by `hunspell-rs v0.3.0`
    ... which is depended on by `cargo-spellcheck v0.4.3`
```

**Expected behavior**
Expect that the installation was successfully completed.
```
✦ ➜ cargo install cargo-spellcheck
    Updating crates.io index
     Ignored package `cargo-spellcheck v0.4.3` is already installed, use --force to override

```
**Screenshots**

![yanked-crate](https://user-images.githubusercontent.com/36624597/90989886-287b0b00-e59d-11ea-8c65-fe53c30cd23a.png)

**Please complete the following information:**
 - System: Ubuntu 18.04.5 LTS
 - Obtained: cargo
 - Version: `v0.4.3`

**Comment by laysauchoa** [comment]
CC @drahnr I am not sure if this is a :bug:  or I am just having a weird error installing it :/

**Comment by drahnr** [comment]
Could you file but g against `hunspell-sys` - it should not depend on a particular patch version imo unless the patch is strictly required.

**Comment by drahnr** [comment]
Accidental close (mobile... )

**Comment by drahnr** [comment]
With path based overrides and the euclio/hunspell-sys#4 applied, things work as expected.

**Comment by euclio** [comment]
A workaround until this is fixed is to `cargo install cargo-spellcheck --locked`.

**Comment by drahnr** [comment]
I guess that should be stated in the readme to avoid this kind of issue popping up again.

**Comment by laysauchoa** [comment]
I still want to be able to build locally to develop. Is there any workaround?

```
✦ ➜ cargo build --locked
    Updating crates.io index
error: failed to select a version for the requirement `bindgen = "^0.54.1"`
  candidate versions found which didn't match: 0.55.0, 0.54.0, 0.53.3, ...
  location searched: crates.io index
required by package `hunspell-sys v0.2.1`
    ... which is depended on by `hunspell-rs v0.3.0`
    ... which is depended on by `cargo-spellcheck v0.4.3-alpha.0 (/home/tmhdev/Documents/cargo-spellcheck)`

```

**Comment by drahnr** [comment]
@laysauchoa could you re-test? It works for me now with the latest master commit (no additional changes necessary).

**Comment by laysauchoa** [comment]
Hi, @drahnr yes, it works now! this issue is resolved! Thank you ^^
