### ISSUE TITLE
Add hacktoberfest label to easy issues 

### ISSUE THREAD

**Issue by laysauchoa** [drahnr/cargo-spellcheck#103]
In order to be discoverable by everybody who are contributing to the hacktoberfest event, the maintainers should mark up some issues with the hacktoberfest label.

https://hacktoberfest.digitalocean.com/

would this be somehow interesting?

**Comment by drahnr** [comment]
@laysauchoa since you are a contributor, can you check if you can add a label? :beginner: is a japanese (iirc) symbol for beginner, so that might be well suited to go into a label like <kbd> :beginner: / hacktoberfest </kbd>

**Comment by drahnr** [comment]
I created the label

**Comment by laysauchoa** [comment]
thanks, it was too fast :)
