### ISSUE TITLE
Custom rule

### ISSUE THREAD

**Issue by TomaszWaszczyk** [drahnr/cargo-spellcheck#112]
** Q: **

Is it possible to make some custom rule, for example here:

https://github.com/paritytech/parity-bridges-common/issues/333

The spellcheck does not make sense, how to make it clean without warning?

**Comment by drahnr** [comment]
The correct approach would be to introduce a custom dictionary with project specific lingo (see in `.config` in this repository for an example.

**Comment by TomaszWaszczyk** [comment]
Appreciate the answer, thanks!
