### ISSUE TITLE
passing files to reflow is not clear

### ISSUE THREAD

**Issue by drahnr** [drahnr/cargo-spellcheck#125]
**Describe the bug**

`cargo spellcheck reflow` does not reflow the whole project if a `Cargo.toml` is present.

**To Reproduce**

Steps to reproduce the behaviour:

1. A file containing `cargo spellcheck reflow`
2. Nothing is reflown
3. `cargo spellcheck reflow src` reflows everything in `src` _recursively_

**Expected behavior**

`cargo spellcheck reflow` works on the same files as `cargo spellcheck check` does.

**Pplease complete the following information:**
 - System: 
 - Obtained:  git
 - Version:  cargo-spellcheck 0.4.7-alpha.0

**Comment by KuabeM** [comment]
I can't reproduce this anymore: running `cargo spellcheck reflow` touches all files in `./` recursively, the same as `cargo spellcheck check` does. Further, appending `src` only causes files in `src` being processed.. so no longer a bug right?

**Comment by drahnr** [comment]
Hmm, I vaguely remember touching some code for this. I might have forgotten to close this.
