### ISSUE TITLE
Clusters eat one character of line endings with two characters

### ISSUE THREAD

**Issue by KuabeM** [drahnr/cargo-spellcheck#135]
**Describe the bug**

In files with `\r\n` as line endings, the last character of the ending '\n' is eaten on constructing the documentation.

I encountered this bug when I tried to debug #124.

**To Reproduce**

Steps to reproduce the behaviour:

1. A file containing `\r\n` as line feeds
2. Run `cargo spellcheck reflow` on that file
3. Results are off and line feeds have changed

**Expected behavior**

A proper reflow.

**Please complete the following information:**
 - System: 
 - Obtained: git
 - Version:  `v0.5.1-alpha.0`

**Additional context**

**Comment by drahnr** [comment]
Good observation! I think this just calls for unification on the line ending parsing detection, usually we can assume that when parsing we have a sliding window of length `2`, and the logic working on that window should consistent whichever component is using it.

**Comment by KuabeM** [comment]
Yes true, we now have multiple locations where we deal with line endings, could be avoided if we already take them into account while parsing.
