### ISSUE TITLE
vulgar fractions and single emojis are detected as mistakes

### ISSUE THREAD

**Issue by drahnr** [drahnr/cargo-spellcheck#141]
**Describe the bug**

`⅔` is marked as error.

**To Reproduce**

Steps to reproduce the behaviour:

1. A file containing `⅔`
2. Run `cargo-spellcheck $file`
3. See the thing marked as possible spelling mistake

**Expected behavior**

Accept it and be happy.

**Please complete the following information:**
 - System:  Fedora
 - Obtained:  cargo
 - Version:

**Comment by drahnr** [comment]
This should be rather simple, checking single characters, that are detected as mistakes, if they are on certain sections of the unicode code pages.

**Comment by laysauchoa** [comment]
I will give it a try, can you assign it to me @drahnr thanks!

**Comment by drahnr** [comment]
Potential solution path: check the character category: https://lib.rs/crates/unicode-general-category
