### ISSUE TITLE
BUG: Failed to guarantee literal content/span integrity

### ISSUE THREAD

**Issue by HCastano** [drahnr/cargo-spellcheck#181]
**Describe the bug**

The CI for the [`ink!` project](https://github.com/paritytech/ink) is logging the following on every run:

```
$ cargo spellcheck check --cfg=.config/cargo_spellcheck.toml --checkers hunspell --code 1
[/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-spellcheck-0.8.4/src/config/args.rs:121] segment = "hunspell"
[2021-06-23T16:59:05Z ERROR cargo_spellcheck::documentation::cluster] BUG: Failed to guarantee literal content/span integrity: Regex should match >r"content"<
[2021-06-23T16:59:05Z ERROR cargo_spellcheck::documentation::cluster] BUG: Failed to guarantee literal content/span integrity: Regex should match >r"a"<
[2021-06-23T16:59:05Z ERROR cargo_spellcheck::documentation::cluster] BUG: Failed to guarantee literal content/span integrity: Regex should match >r"b"<
[2021-06-23T16:59:05Z ERROR cargo_spellcheck::documentation::cluster] BUG: Failed to guarantee literal content/span integrity: Regex should match >r"c"<
[2021-06-23T16:59:05Z ERROR cargo_spellcheck::documentation::cluster] BUG: Failed to guarantee literal content/span integrity: Regex should match >r"d"<
[2021-06-23T16:59:05Z ERROR cargo_spellcheck::documentation::cluster] BUG: Failed to guarantee literal content/span integrity: Regex should match >r"e"<
```

I've also seen some spurious failures and I wonder if they're related to this. For example, I opened [a PR](https://github.com/paritytech/ink/pull/828) in which the `spellcheck` [check passed](https://gitlab.parity.io/parity/ink/-/jobs/982626), but as soon as the PR hit `master` and the same check ran [it failed](https://gitlab.parity.io/parity/ink/-/jobs/985392).

**To Reproduce**

```
git clone https://github.com/paritytech/ink
cd ink
cargo spellcheck check --cfg=.config/cargo_spellcheck.toml --checkers hunspell --code 1
```

**Expected behavior**

I expect the spellchecker to run without printing any warnings, and to either pass or fail consistently.

**Comment by drahnr** [comment]
Which version is currently in use with ink?

**Comment by drahnr** [comment]
I think there are at least two issues here:

a) the regex to determine the comment type, expected at least one pound character for raw strings which is wrong.
b) traversing seems to be slightly messed up, when I run it locally, I get 
```
error: spellcheck(Hunspell)
   --> /tmp/ink/crates/env/src/chain_extension.rs:58
    |
 58 |    All tuple types that may act as input parameters for the chain extension method are valid.
    |        ^^^^^
    | - tulle, duple, or letup
    |
    |   Possible spelling mistake found.

error: spellcheck(Hunspell)
    --> /tmp/ink/crates/env/src/chain_extension.rs:101
     |
 101 |  All tuple types that may act as input parameters for the chain extension method are valid.
     |      ^^^^^
     | - tulle, duple, or letup
     |
     |   Possible spelling mistake found.

error: spellcheck(Hunspell)
    --> /tmp/ink/crates/env/src/engine/experimental_off_chain/test_api.rs:276
     |
 276 |  Alice, Bob, Charlie, Django, Eve and Frank.
     |                       ^^^^^^
     | - Fandango
     |
     |   Possible spelling mistake found.

error: spellcheck(Hunspell)
    --> /tmp/ink/crates/env/src/engine/off_chain/test_api.rs:292
     |
 292 |  Alice, Bob, Charlie, Django, Eve and Frank.
     |                       ^^^^^^
     | - Fandango
     |
     |   Possible spelling mistake found.
// snip
```
w/ `ink!` version `98bf5a9960`. So some files are just not checked every time :monocle_face: though this is actually unit tested. If you increase logging with `-vvvv` you can watch out for `🥞` which is used for the folder traversal, though this is rather mundane to do in a large~ish project.

Investigating...

**Comment by drahnr** [comment]
Note that between the PR CI run and the `master` run you have two different container versions which _could_ have two different `en_US.dic` in the image, and as such it's not idempotent anymore.

For this purpose there are two recently (`0.8.x`) introduced config items which are not use in the `ink` config as far as I can see:

```
# If set to `true`, the OS specific default search paths
# are skipped and only explicitly specified ones are used.
skip_os_lookups = false

# Use the builtin dictionaries if none were found in
# in the configured lookup paths.
# Usually combined with `skip_os_lookups=true`
# to enforce the `builtin` usage for consistent
# results across distributions and CI runs.
# Setting this will still use the dictionaries
# specified in `extra_dictionaries = [..]`
# for topic specific lingo.
use_builtin = true
```

**Comment by HCastano** [comment]
Thanks for looking into this @drahnr!

> Note that between the PR CI run and the `master` run you have two different container versions which _could_ have two different `en_US.dic` in the image, and as such it's not idempotent anymore.

Good point. However, I believe the only differences between the containers are the version of `nightly` Rust which is used.

> For this purpose there are two recently (`0.8.x`) introduced config items which are not use in the `ink` config as far as I can see:
> 
> ```
> # If set to `true`, the OS specific default search paths
> # are skipped and only explicitly specified ones are used.
> skip_os_lookups = false
> 
> # Use the builtin dictionaries if none were found in
> # in the configured lookup paths.
> # Usually combined with `skip_os_lookups=true`
> # to enforce the `builtin` usage for consistent
> # results across distributions and CI runs.
> # Setting this will still use the dictionaries
> # specified in `extra_dictionaries = [..]`
> # for topic specific lingo.
> use_builtin = true
> ```

Okay, I'll add these to the ink! CI.

**Comment by drahnr** [comment]
Feel free to re-open this if it persists, but with the `use_builtin = false` and `skip_os_lookups = true` this should become deterministic. If not, I would appreciate a log with `-vvv` for both runs so I can diff and maybe gain some additional differences.

**Comment by HCastano** [comment]
> ... but with the `use_builtin = false` and `skip_os_lookups = true` this should become deterministic and independent of the container or OS. 

Do you mean `use_builtin = true`? How else will `cargo-spellcheck` know what dictionary to use?

**Comment by drahnr** [comment]
Ah yes, my fault!
