### ISSUE TITLE
Installing fails

### ISSUE THREAD

**Issue by matthiasbeyer** [drahnr/cargo-spellcheck#184]
**Describe the bug**

Installing with cargo failed.

**To Reproduce**

Steps to reproduce the behaviour:

1. `cargo install cargo-spellcheck`

```
error: failed to compile `cargo-spellcheck v0.8.6`, intermediate artifacts can be found at `/tmp/cargo-installtdLs7F`

Caused by:
  failed to parse manifest at `/home/beyer/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_syntax-0.0.61/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```

**Expected behavior**

Installation works.

**Please complete the following information:**
 - System: centos7
 - Obtained: cargo
 - Version: latest

**Comment by drahnr** [comment]
Which `cargo` and `rustc` version do you use? I think this looks like the `Cargo.lock` `Cargo.toml` have keys that are only understood by your current `cargo` when adding the shown `cargo-features = ["resolver"]` to the manifest.

How did you install `cargo`? Via your OS pkgs or via `yum`/`dnf`?

Could you provide:

`rustc --version`
`cargo --version`

Ty!

**Comment by matthiasbeyer** [comment]
```
$ rustc --version
rustc 1.50.0 (cb75ad5db 2021-02-10)
$ cargo --version
cargo 1.50.0 (f04e7fab7 2021-02-04)
```

installed via rustup

**Comment by drahnr** [comment]
According to https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html `1.51.0` is when the new resolver did hit stable. But this should be documented in the `README.md` either way. Thank for reporting!
