### ISSUE TITLE
Non-idempotent results for recurring CI check runs

### ISSUE THREAD

**Issue by cmichi** [drahnr/cargo-spellcheck#187]
**Describe the bug**

* We currently have the ink! master CI failing due to some words which were previously not found, even though the CI was green for the PR's. This is the job from `master`: https://gitlab.parity.io/parity/ink/-/jobs/1012438.

I've created [this PR](https://github.com/paritytech/ink/pull/855) branched from the above `master` to fix those issues. The CI for that PR is green. This is the job: https://gitlab.parity.io/parity/ink/-/jobs/1011563.

I've created [another PR](https://github.com/paritytech/ink/pull/856) from the same `master` commit. The CI there fails due to a spellcheck error which hasn't shown up anywhere else before. This is the job: https://gitlab.parity.io/parity/ink/-/jobs/1012289.

**Expected behavior**

I would have expected the last spelling mistake ("reorg") to show up in either the `master` CI run or the run on https://github.com/paritytech/ink/pull/855, but it did in neither.

**Comment by drahnr** [comment]
Could we add a `cargo spellcheck --version`? That would simplify diagnostics quite a bit since I started doing smaller and faster iterations.

**Comment by TriplEight** [comment]
I'm running it [slightly different](https://github.com/paritytech/polkadot/pull/3421/files#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7R176-R177): adding `-r $(git diff --name-only ${CI_COMMIT_SHA} ${CI_DEFAULT_BRANCH})` at the end. But evidently, it does not work: the amount of changed files in the PR is 230 and growing. One of the reasons might be in GitLab, it can't find the default branch to compare with:

```bash
$ time cargo spellcheck check -vvv --cfg=scripts/gitlab/spellcheck.toml --checkers hunspell --code 1 -r $(git diff --name-only ${CI_COMMIT_SHA} ${CI_DEFAULT_BRANCH})
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Parsing the git diff won't be necessary as soon as the whole code is covered by the check, but it seems like something makes `spellcheck` quit early sometimes.
Same I can conclude from @cmichi 's example, he doesn't parse the git diff.

**Comment by drahnr** [comment]
With #190 all files checked will be visible with `-vv` or higher logging verbosity. So this should become easier to investigate.

**Comment by drahnr** [comment]
`v0.8.9` got released just now, which should provide enough information to resolve this. If it turns out it's not gitlab's env lacking, please re-open!
