### ISSUE TITLE
Can this be used to spellcheck symbol names in code, not just documentation and comments?

### ISSUE THREAD

**Issue by Keavon** [drahnr/cargo-spellcheck#196]
For my [project](https://github.com/GraphiteEditor/Graphite) (written in Rust and a web component in TypeScript and Vue), I am interested in adding a CI checker to detect spelling errors in the variable/function/etc. names that people contribute, perhaps with a global whitelist file to squelch false positives. Is this tool capable of that, or does it only target documentation and comments as I could glean from the project description?

**Comment by drahnr** [comment]
Hey, thanks for reaching out!

This will eventually meander into scope of `cargo-spellcheck`, but this is not an easy problem. Variable names are not necessarily predictable and abbreviations are possible, i.e `impl_foo`. And that is the main issue for implementing that issue besides a general lack of time.

If you are interested, I'd be happy to mentor you implementing it!

**Comment by Keavon** [comment]
Good to know where the project is headed. My hands are full so I unfortunately can't help with this, but I'll be sure to keep an eye on the project into the future. Thanks for creating it.

**Comment by drahnr** [comment]
Closing this in favor of #208
