### ISSUE TITLE
default look up hunspell dirs

### ISSUE THREAD

**Issue by zhiburt** [drahnr/cargo-spellcheck#21]
Hey @drahnr, I've seen your crate on rust weekly, and came here :). I just started with this crate so might I misunderstand something.

I am recently got set up an `Arch` distribution. And find out that it seems that `pacman` put `hunspell` dictionaries to `/usr/share/myspell/dicts`. This causes an inability to start `--interactive` mode. But `spellcheck` itself works.

```bash
[zhiburt@zhiburt scc]$ cargo spellcheck fix --interactive
error: /usr/share/myspell/en_US.aff: cannot open
error: /usr/share/myspell/en_US.dic: cannot open
error: /usr/share/myspell/en_US.aff: cannot open
Path is /home/zhiburt/proj/scc/src/main.rs and has 59
```

```bash
[zhiburt@zhiburt ~]$ ls -l /usr/share/myspell/
total 4
drwxr-xr-x 2 root root 4096 Jun 14 00:05 dicts
[zhiburt@zhiburt ~]$ ls -l /usr/share/myspell/dicts/
total 0
lrwxrwxrwx 1 root root 29 Feb 23 12:06 en_US.aff -> /usr/share/hunspell/en_US.aff
lrwxrwxrwx 1 root root 29 Feb 23 12:06 en_US.dic -> /usr/share/hunspell/en_US.dic
lrwxrwxrwx 1 root root 35 Feb 23 12:06 en_US-large.aff -> /usr/share/hunspell/en_US-large.aff
lrwxrwxrwx 1 root root 35 Feb 23 12:06 en_US-large.dic -> /usr/share/hunspell/en_US-large.dic
```

I resolved the issue just by moving the files to parent directory. But if the issue occurred itself not only on `arch`,  I think that may adding a dict path to the look up places a good idea.

https://github.com/drahnr/cargo-spellcheck/blob/e321dcc912974adc559f3422cc263178da769bb8/src/config.rs#L46

And I also checked the logs by setting `CARGO_SPELLCHECK=cargo_spellcheck=trace`, and noticed something. Is it supposed to continue analyzing the text even though it got an `hunspell` issue.

```log
[2020-06-13T21:19:44Z DEBUG cargo_spellcheck::checker] Running Hunspell checks
error: /usr/share/myspell/en_US.aff: cannot open
error: /usr/share/myspell/en_US.dic: cannot open
error: /usr/share/myspell/en_US.aff: cannot open
[2020-06-13T21:19:44Z TRACE cargo_spellcheck::markdown] Parsing event (1..68): Start(Paragraph)
[2020-06-13T21:19:44Z TRACE cargo_spellcheck::markdown] Parsing event (1..68): Text(Borrowed("Prints shall tokens which are produced by lexical analyzer to outdo"))
[2020-06-13T21:19:44Z TRACE cargo_spellcheck::markdown] Parsing event (1..68): End(Paragraph)
```

**Comment by zhiburt** [comment]
By the way it also can be solved by config.

**Comment by drahnr** [comment]
Hi @zhiburt thanks for the report!

I was not aware of Arch deviating from Fedora hunspell, so adding an additional default path sounds good to me.

There should be no difference in behaviour between `check` and `fix -i` runs in error behaviour.

Since you already looked into the code, I'd be happy to include your fix - if not I'll impl smth in the next few days
