### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by lopopolo** [drahnr/cargo-spellcheck#225]
(I'm not sure if posting thanks via an issue is welcome 😅)

Thank you for this tool! I'm not sure if you have a trophy case, but I was able to correct 400+ spelling errors in one of my projects:

- https://github.com/artichoke/artichoke/pull/1457

Cheers 🍻

**Comment by lopopolo** [comment]
feel free to close this, there is no action to take here on my end.

**Comment by drahnr** [comment]
Hey @lopopolo , I very much appreciated feedback :+1: , especially (but not limited to) the positive :upside_down_face: Thank you!
