### ISSUE TITLE
Check `description` field in `Cargo.toml` for typos

### ISSUE THREAD

**Issue by lopopolo** [drahnr/cargo-spellcheck#233]
**Is your feature request related to a particular use-case?**

I published a crate to crates.io with a typo in the `description` field in `Cargo.toml`.

**Describe the solution you'd like to implement/see implemented**

Perform spellchecking on the `description` field in `Cargo.toml`.

**Describe alternatives you've considered**

code review, post-publish review.

**Additional context**

**Comment by drahnr** [comment]
There is only a small chunk of code missing to make this functional, adding another match arm to handle `ChevkEntity::ManifestDesctiption` in https://github.com/drahnr/cargo-spellcheck/blob/748b4f0bcec477695eb7ade98a01f03634efe277/src/traverse/mod.rs#L555

**Comment by lopopolo** [comment]
Thanks for the pointer @drahnr.

I put up a WIP PR here:

- https://github.com/drahnr/cargo-spellcheck/pull/235
