### ISSUE TITLE
Not catching spelling issues within a unit test code comment

### ISSUE THREAD

**Issue by emostov** [drahnr/cargo-spellcheck#237]
**Describe the bug**

Here: https://github.com/paritytech/polkadot/pull/4318/files/c388e2b8389aa612f7d1324eb3bd9dcd96d0145f#diff-96cf9e8e82a1dd396d7879f319bb42d598f71e2ddf23237c290c7655c7bea895L1220 we have the comment:

```
// No backed and concluding cores, so all cores will be fileld with disputesw
```

Both `fileld` and `disputesw` are not valid english words.

**To Reproduce**

Steps to reproduce the behaviour:

TODO I will come back to this soon to see if the issue can be reproduced with a minimal example, but for now checking out commit d21e86d2212378400f3761b83e6697c8cb27505e on the polkadot repo and then running `cargo spellcheck list-files` (The exact command the CI runs is cargo spellcheck list-files -vvv $(git diff --diff-filter=AM --name-only $(git merge-base ${CI_COMMIT_SHA} ${CI_DEFAULT_BRANCH} -- :^bridges)))

**Expected behavior**

There should have been a warning for the words "fileld" and "disputesw"

**Please complete the following information:**
 - System: Debian
 - Obtained: cargo
 - Version: cargo-spellcheck 0.9.3

**Additional context**
This spellcheck takes place as a CI process which is configured https://github.com/paritytech/polkadot/blob/master/scripts/gitlab/spellcheck.toml. I am not sure how this works though

**Comment by drahnr** [comment]
Did you run it with `--dev` so `//` are picked up as well?

**Comment by emostov** [comment]
Tbh I have not run locally at all

**Comment by drahnr** [comment]
Alright, then I'll close this :)
