### ISSUE TITLE
Spellcheck should ignore capitalization

### ISSUE THREAD

**Issue by jyn514** [drahnr/cargo-spellcheck#261]
**Describe the bug**

```
error: spellcheck(Hunspell)
     --> rust/library/std/src/path.rs:2031
      |
 2031 |  Calling `to_string_lossy` on a `Path` with valid unicode:
      |                                                   ^^^^^^^
      | - Unicode, uni code, uni-code, or unicorn
      |
      |   Possible spelling mistake found.
```
It's technically right, the proper casing is "Unicode", but this seems unnecessarily pedantic.

**To Reproduce**

Steps to reproduce the behaviour:

1. A file containing `unicode`
2. Run `cargo spellcheck ...`
3. ...

cc https://github.com/rust-lang/rust/issues/74697

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - System: 
 - Obtained: 
 - Version: 

**Additional context**

**Comment by drahnr** [comment]
If you think this is ok for your local codebase, I'd expect `unicode` to be added to a project specific dictionary file. `Unicode` after all, is the correct term.

**Comment by drahnr** [comment]
I don't think there is a systematic approach to this, other than allowing extra word's as part of a custom dictionary which is already supported. Generally disabling capitalization / casing entirely.

If you think that doesn't cover it, happy to discuss this further
