### ISSUE TITLE
NlpRules checker can not be enabled

### ISSUE THREAD

**Issue by ravenexp** [drahnr/cargo-spellcheck#270]
**Describe the bug**

```
cargo-spellcheck --checkers nlprules
```

uses Hunspell checker only, and does not enable NlpRules.

**To Reproduce**

1. Run

```
cargo-spellcheck -vvv --checkers nlprules
```

2. Get

```
...
[2022-08-17T09:48:17Z DEBUG cargo_spellcheck::checker] Enabling Hunspell checks.
...
[2022-08-17T09:48:17Z DEBUG cargo_spellcheck::checker] Checker NlpRules is disabled by configuration.
...
```

**Expected behavior**

NlpRules is enabled, and Hunspell is disabled.

**Please complete the following information:**
 - System: Arch Linux
 - Obtained: pacman
 - Version: cargo-spellcheck 0.11.2

**Comment by drahnr** [comment]
Known issue, introduced in #243 iirc and fixed in master
