### ISSUE TITLE
Help identifying panic: `assertion failed: plain_range.start <= plain_range.end` 

### ISSUE THREAD

**Issue by dutterbutter** [drahnr/cargo-spellcheck#318]
** Q: **

I am using `cargo-spellcheck` in my repo and with `dev_comments` set to `true` I receive this panic error:
```
cargo spellcheck --cfg=./spellcheck/era.cfg
The application panicked (crashed).
Message:  assertion failed: plain_range.start <= plain_range.end
Location: /Users/dustinbrickwood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/doc-chunks-0.0.5/src/markdown.rs:363

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

When I run with `-vvvvv` verbosity it doesn't seem to panic but perhaps I reading it wrong? Also ran with `RUST_BACKTRACE=full` but no clarity on the root issue is. 

**Question:** How can I see where in my application it is causing this panic?

### To reproduce

1. `git clone git@github.com:matter-labs/zksync-era.git` 
2. `git checkout dutterbutter-pla-646-add-spelling-linter-for-zksync-era-core-part-2`
3. `cargo spellcheck --cfg=./spellcheck/era.cfg --code 1` 
4. Error result:
```
The application panicked (crashed).
Message:  assertion failed: plain_range.start <= plain_range.end
Location: /Users/dustinbrickwood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/doc-chunks-0.0.5/src/markdown.rs:363

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

### cargo-spellcheck Config file:

<details>
  <summary>Click to view config file</summary>

 ```
 # Project settings where a Cargo.toml exists and is passed
# ${CARGO_MANIFEST_DIR}/.config/spellcheck.toml

# Also take into account developer comments
dev_comments = true

# Skip the README.md file as defined in the cargo manifest
skip_readme = false

[Hunspell]
# lang and name of `.dic` file
lang = "en_US"
# OS specific additives
# Linux: [ /usr/share/myspell ]
# Windows: []
# macOS [ /home/alice/Libraries/hunspell, /Libraries/hunspell ]

# Additional search paths, which take presedence over the default
# os specific search dirs, searched in order, defaults last
search_dirs = ["."]

# Adds additional dictionaries, can be specified as
# absolute paths or relative in the search dirs (in this order).
# Relative paths are resolved relative to the configuration file
# which is used.
# Refer to `man 5 hunspell`
# or https://www.systutorials.com/docs/linux/man/4-hunspell/#lbAE
# on how to define a custom dictionary file.
extra_dictionaries = ["era.dic"]

# If set to `true`, the OS specific default search paths
# are skipped and only explicitly specified ones are used.
skip_os_lookups = false

# Use the builtin dictionaries if none were found in
# in the configured lookup paths.
# Usually combined with `skip_os_lookups=true`
# to enforce the `builtin` usage for consistent
# results across distributions and CI runs.
# Setting this will still use the dictionaries
# specified in `extra_dictionaries = [..]`
# for topic specific lingo.
use_builtin = true


[Hunspell.quirks]
# Transforms words that are provided by the tokenizer
# into word fragments based on the capture groups which are to
# be checked.
# If no capture groups are present, the matched word is whitelisted.
transform_regex = ["^'([^\\s])'$", "^[0-9]+x$"]
# Accepts `alphabeta` variants if the checker provides a replacement suggestion
# of `alpha-beta`.
allow_concatenation = true
# And the counterpart, which accepts words with dashes, when the suggestion has
# recommendations without the dashes. This is less common.
allow_dashed = false

[NlpRules]
# Allows the user to override the default included
# exports of LanguageTool, with other custom
# languages

# override_rules = "/path/to/rules_binencoded.bin"
# override_tokenizer = "/path/to/tokenizer_binencoded.bin"

[Reflow]
# Reflows doc comments to adhere to a given maximum line width limit.
max_line_length = 80
```

</details>

**Version:**
```
cargo spellcheck --version
cargo-spellcheck 0.13.1
```

Any assistance here would be greatly appreciated 🙏 Thanks!

**Comment by drahnr** [comment]
Could you share the repository in question with me? Otherwise I'd recommend to find the particular file in question by running spell check on each file

**Comment by dutterbutter** [comment]
@drahnr repo is: [zksync-era](https://github.com/matter-labs/zksync-era/tree/dutterbutter-pla-646-add-spelling-linter-for-zksync-era-core-part-2)

branch: `dutterbutter-pla-646-add-spelling-linter-for-zksync-era-core-part-2`

**Comment by dutterbutter** [comment]
@drahnr alright I seem to have narrowed it down but I still don't see what is causing the crash in order for me to fix it. The issue is specifically when I run:

`cargo spellcheck -vvv --cfg=../../../spellcheck/era.cfg .` in this directory: https://github.com/matter-labs/zksync-era/tree/main/core/lib/multivm

However, if I run `cargo-spellcheck` inside each of the nested directories it does not crash? 

Running with `-vvv` I see this now:

```
[2023-12-06T01:54:05Z DEBUG hunspell] Errorfunctionsel --{suggest}--> ["Perfunctorily"]
[2023-12-06T01:54:05Z INFO  cargo_spellcheck::action] ✅ /Users/dustinbrickwood/Documents/dev/zk/zksync-era/core/lib/multivm/src/interface/types/errors/vm_revert_reason.rs
[2023-12-06T01:54:05Z DEBUG hunspell] stopreasonVmExec --{suggest}--> []
[2023-12-06T01:54:05Z DEBUG hunspell] Ocallstackdepth --{suggest}--> []
The application panicked (crashed).
Message:  assertion failed: plain_range.start <= plain_range.end
Location: /Users/dustinbrickwood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/doc-chunks-0.0.5/src/markdown.rs:363

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[2023-12-06T01:54:05Z DEBUG hunspell] VmTracer --{suggest}--> []
``` 

Again, I don't see the issue but it could be staring at me in the face.

**Comment by dutterbutter** [comment]
Thanks @drahnr 

**Relevant info:**

OS: MacOs 14.1.1 (Sonoma)
Git Sha: [878fd2d](https://github.com/matter-labs/zksync-era/commit/878fd2d8678777ac50ae44b1ea0f98ff6ae60333)
Cargo-spellcheck version: cargo-spellcheck 0.13.1

As soon as I run `cargo spellcheck --cfg=./spellcheck/era.cfg --code 1` I receive the panic so there is no output other than the provided error message. 

I will try to run on a linux machine to see if its specific to my environment.

**Comment by dutterbutter** [comment]
Also crashes on linux / CI :(

**Comment by drahnr** [comment]
Your branch does trigger it, `main` does not.

**Comment by drahnr** [comment]
It turns out it only happens when run as a directory, single files don't trigger it. `-j1` also does not trigger it. I run it on a 64 threads machine.

**Comment by dutterbutter** [comment]
@drahnr thanks for investigating. Truly appreciate it. 

Can you elaborate on "-j1 also does not trigger it". When I run it with `cargo spellcheck -j1 --cfg=./spellcheck/era.cfg --code 1` it still triggers a panic.

**Comment by drahnr** [comment]
`RUST_BACKTRACE=1 cargo-spellcheck --cfg=../../../spellcheck/era.cfg --code 1 -j1 /media/supersonic1t/projects/zksync-era/core/lib/multivm/src/versions/vm_m6/tests/bootloader.rs` fails reproducibly

**Comment by dutterbutter** [comment]
Thank you very much for your support here. Top notch for OS ❤️ Let me test on my side and then I can close accordingly.

**Comment by drahnr** [comment]
Re-opening, it's not acceptable for `cargo-spellcheck` to crash and burn.
