### ISSUE TITLE
question: debug process of interactive mode by printing

### ISSUE THREAD

**Issue by zhiburt** [drahnr/cargo-spellcheck#33]
## Summary

Putting something in stdout frequently be a caused issues of displaying correct interface. I guess it's related to the usage of `raw_mode`.

Why it has a little importance because in debuging process you think that any issue may be caused by the debug changes.

For example adding a debug message in select_next will not work out properly.

```diff
     pub fn select_next(&mut self) {
+        dbg!(&self.pick_idx);
         self.pick_idx = (self.pick_idx + 1).rem_euclid(self.n_items);
     }
```

It copy the chosen line on each typing.

```
error: spellcheck(Hunspell)
    --> /home/zhiburt/proj/cargo-spellcheck/src/literalset.rs:176
     |
 176 |  but also the `LineColumn` in the proc_macro2 context.
     |                                   ^^^^^^^^^^^

(6/8) Apply this suggestion [y,n,q,a,d,j,e,?]?
 » macrocosmic
   ...
```

After some typing

```
   ...
   macrocosmic
 » macrocosmic
 » macrocosmic
 » macrocosmic
 » macrocosmic
 » macrocosmic
   macrocosmic
   macrocosmic
   macrocosmic
 » ...
```

Might debugging information to file here is not a bad idea? Or it's a bad idea ...

## Context

* Prior discussion: low

**Comment by drahnr** [comment]
The only workaround I can currently see, is to use the `ScopedRaw` on a more granular level. But I am not sure if done too tightly, around `read!(..)` that we might queued events - frankly I know too little about the terminal mechanics to make a good judgement here.

But I fully agree that the current situation is not optimal - one way is to avoid debugging by means of `println!` and resort to lldb, but that might be not satisfactory for issues on a bigger scale which are being triaged.

**Comment by drahnr** [comment]
Frankly, I think the only sane approach for this is to use a debugger like `lldb` besides what is already said.
