### ISSUE TITLE
on panic, raw terminal mode is not left

### ISSUE THREAD

**Issue by drahnr** [drahnr/cargo-spellcheck#34]
## Summary

running into `unimplemented!` or being terminated via `kill -9`, the terminal is stuck in raw mode

## Steps to reproduce

`cargo spellcheck fix -i &; kill -9 $!`

## Expected results

terminal should return to it's previous state

## Actual results

terminal is stuck in raw mode

## Triaging info

* Version: 0.2.1
* Did this used to work? Nope

**Comment by drahnr** [comment]
Consider using https://lib.rs/crates/termios combined with maybe libc?

**Comment by drahnr** [comment]
Testcases:
 * `kill $PID`
 * `kill -9 $PID`
 * <kbd>CTRL</kbd>+<kbd>C</kbd>

**Comment by KuabeM** [comment]
From `man atexit`: 

> Functions registered using atexit() (and on_exit(3)) are not called
> if a process terminates abnormally because of the delivery of a
> signal.

I don't think there's a way to handle `SIGKILL`. For all other signals, I suggest we use [signal-hook](https://lib.rs/crates/signal-hook)
