### ISSUE TITLE
reflow documentation comments + markdown files

### ISSUE THREAD

**Issue by drahnr** [drahnr/cargo-spellcheck#39]
## Summary

Wrapping of doc comments is a nice addition to make the comments look nicer in code.

Probably requires a new set of parameters, i.e. line width (soft and hard limits) and how to deal with extra long link descriptions.

**Comment by drahnr** [comment]
Textwrap already does something very similar https://crates.io/crates/textwrap

**Comment by KuabeM** [comment]
I was just about to post my 'algorithm'... That's convenient!

**Comment by drahnr** [comment]
Did not mean to interfere, mostly a pointer how we could approach it - the above is not markdown/cmark aware iiuc so that might still be a need for some algorithm work :)
