### ISSUE TITLE
ellipsize overly long statements

### ISSUE THREAD

**Issue by drahnr** [drahnr/cargo-spellcheck#42]
## Summary

When a individual line is longer than the terminal size, it should be ellipsized with `...`. Should probably be part of `LiteralSet`'s `fmt::Display` impl.

Relevant files: `literal*.rs`

**Comment by laysauchoa** [comment]
Please, assignee to me if no one is working on it. I need some time to understand the code though. 

This shall be modified: https://github.com/drahnr/cargo-spellcheck/blob/master/src/literalset.rs#L384

Can you point me where to find more info about terminal size in the code? Thank you!

**Comment by drahnr** [comment]
https://github.com/drahnr/cargo-spellcheck/blob/a26aee13113292f132774687ce1932807dc797b6/src/suggestion.rs#L67 this is the implementation that's supposed to be adapted, the crate being used should have functionality to determine the size, if not, `crossterm` has it for sure, but itmight be a bit of an overkill for that and would introduce more complexity than needed
