### ISSUE TITLE
Signal thread panic if the `stdout` is redirected

### ISSUE THREAD

**Issue by zhiburt** [drahnr/cargo-spellcheck#59]
**Overview**

I was willing to use `grep` on the `spellcheck` output and noticed that redirecting output by `>` or `|` will cause panic.
I see that the real output goes to `stderr` so it's not crucial.
I decided just to publish that but it's certainly not critical, even though hard to say why that's raised.

**Reproduction**

```bash
[zhiburt@zhiburt cargo-spellcheck]$ cargo spellcheck | grep ".md"
thread '<unnamed>' panicked at 'Failed to get stdout: Os { code: 25, kind: Other, message: "Inappropriate ioctl for device" }', src/main.rs:87:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

Probably don't having panic is a good one.

**Pplease complete the following information:**
 - System: Arch
 - Obtained: git `4dd8e0666b6c373d04f09fcd7b42a270e7c4fad9`
 - Version: `cargo-spellcheck 0.3.0-alpha.1`

**Comment by drahnr** [comment]
@KuabeM I think this is caused by the latest changes, where we rely on stdout existing - now there are two things, handling stderr and handling errors gracefully

**Comment by drahnr** [comment]
Very likely to be one of those https://github.com/drahnr/cargo-spellcheck/blob/master/src/main.rs#L86-L89

Will add a simplistic CI test.

**Comment by KuabeM** [comment]
I'm looking into it and make a PR together with the cursor issue.
