### ISSUE TITLE
output format is garbaled since v0.3.0-alpha.1

### ISSUE THREAD

**Issue by drahnr** [drahnr/cargo-spellcheck#68]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'cargo spellcheck check'
3. Observe garbled rendering, `^^^^` are missing and the erronous line is not rendered

**Expected behavior**

The line to be rendered with `^^^^` underneath the erroneous word.

**Screenshots**

![image](https://user-images.githubusercontent.com/667047/87010232-8eb2f680-c1c6-11ea-8edd-2148ae3d21aa.png)

**Pplease complete the following information:**
 - System: Fedora 32
 - Obtained:cargo
 - Version: `cargo-spellcheck 0.3.0-alpha.1`

**Comment by drahnr** [comment]
Related: #25

**Comment by drahnr** [comment]
The output for multiple lines is still not functional and must be improved, possibly as part of #65 or in a separate PR.

**Comment by zhiburt** [comment]
Specifically`^^^` sign is shifted from time to time as I see

```
[zhiburt@zhiburt cargo-spellcheck]$ cargo spellcheck
error: spellcheck(Hunspell)
  --> /home/zhiburt/proj/cargo-spellcheck/src/checker/mod.rs:5
   |
 5 |  Checker

 Trait to handle additional trackers.
 Contains also helpers to avoid re-implementing generic
 algorithms again and again, i.e. tokenization.
   |                                                                                                                                           ^^^^^^^^^^^^
   | - autoionization or ionization
   |
   |   Possible spelling mistake found.
   |
```

I'd wanted to created an issue according to it but I've noticed this issue already exists :+1:
