### ISSUE TITLE
What if config is empty?

### ISSUE THREAD

**Issue by zhiburt** [drahnr/cargo-spellcheck#85]
When used an empty or wrong config the `cargo-spellcheck` doesn't stop it's processing as well it doesn't tries to get back to the default settings.

As shows in #84 `Config` in this situation is `Config { hunspell: None, languagetool: None }`.

There may be we could handle this situation better for example.
1. Stop right when we have incomplete `config`. Do not process any files as there's no matter to carry on (I guess).
2. Raise an error/message to a user which denotes that the `config` was given is incomplete and `spellcheck` can't proceed. 
3. Continue with default `config`.

**Comment by zhiburt** [comment]
As i see there's a logic already which use a default config if there was a error in parsing.

https://github.com/drahnr/cargo-spellcheck/blob/74589819974936f6b6eaa1f2df7932a5fb7d8caa/src/main.rs#L229-L245

**Comment by drahnr** [comment]
I think it needs to be decided what should be the use case? How does the toml lib handle this? For `Option<_>`-al sections this should just be `None` and filled up with `Default`-values

**Comment by drahnr** [comment]
If the config is empty, the default impl will be used.
