### ISSUE TITLE
Show less whitespace if there is no spelling suggestion

### ISSUE THREAD

**Issue by jyn514** [drahnr/cargo-spellcheck#93]
**Is your feature request related to a use-case? Please describe.**
Running this on rustc gave (among many others) the following error:

```
error: spellcheck(Hunspell)
   --> /home/joshua/rustc/src/tools/rustfmt/src/config/options.rs:74
    |
 74 |  No spaces around "=" and "+"
    |                    ^
    |
    |
    |   Possible spelling mistake found.
    |
```

Note that this has 2 full blank lines, as well as a line that's almost empty except for the `^`.

**Describe the solution you'd like**
It would be nice if it showed less whitespace, something like

```
error: spellcheck(Hunspell)
   --> /home/joshua/rustc/src/tools/rustfmt/src/config/options.rs:74
    |
 74 |  No spaces around "=" and "+"
    |                    ^
    |   Possible spelling mistake found.
```

Additionally, it would be nice to get rid of the trailing blank line even if there were suggestions (the last line with only `    |`):
```
error: spellcheck(Hunspell)
   --> /home/joshua/rustc/src/tools/rustfmt/src/config/options.rs:72
    |
 72 |  Spacing around type combinators.
    |                      ^^^^^^^^^^^
    | - combinations, combination, contaminators, or coordinators
    |
    |   Possible spelling mistake found.
    |
```

**Describe alternatives you've considered**
- Don't change the format. The errors will take up more space in the terminal but work fine otherwise.
- Use a different format than the one I suggested here. Of course I prefer mine but there might be others with less whitespace and more consistent with the existing format.

**Comment by drahnr** [comment]
@laysauchoa do you want to take a stab at this?

**Comment by laysauchoa** [comment]
please, @drahnr assign it to me. I will have more time to work on this now.

**Comment by laysauchoa** [comment]
Thanks! @drahnr
